EVENT_LIBRARY_INDEXED = "library_indexed"
EVENT_METADATA_DRAFT_GENERATED = "metadata_draft_generated"
EVENT_BOOK_RAG_QUESTION_ASKED = "book_rag_question_asked"
EVENT_MULTI_BOOK_RAG_QUESTION_ASKED = "multi_book_rag_question_asked"
EVENT_NOTE_CREATED = "note_created"
EVENT_NOTE_FROM_CHAT_CREATED = "note_from_chat_created"
EVENT_NOTE_EXPORTED = "note_exported"
EVENT_NOTE_WORKSPACE_EXPORTED = "note_workspace_exported"

SOURCE_LIBRARY = "library"
SOURCE_RAG = "rag"
SOURCE_NOTES = "notes"
SOURCE_SYSTEM = "system"

LEARNING_EVENT_TYPES = {
    EVENT_LIBRARY_INDEXED,
    EVENT_METADATA_DRAFT_GENERATED,
    EVENT_BOOK_RAG_QUESTION_ASKED,
    EVENT_MULTI_BOOK_RAG_QUESTION_ASKED,
    EVENT_NOTE_CREATED,
    EVENT_NOTE_FROM_CHAT_CREATED,
    EVENT_NOTE_EXPORTED,
    EVENT_NOTE_WORKSPACE_EXPORTED,
}
